### ISSUE TITLE
微博上传图片 302重定向返回ret=-4 没有返回pid怎么回事啊 Location: https://weibo.com/aj/static/upimgback.html?_wv=5&callback=STK_ijax_1557910848318&ret=-4

### ISSUE THREAD

**Issue by bensonX** [wu529778790/pic.shenzjd.com#1]
微博上传图片 302重定向返回ret=-4 没有返回pid怎么回事啊 Location: https://weibo.com/aj/static/upimgback.html?_wv=5&callback=STK_ijax_1557910848318&ret=-4

**Comment by wu529778790** [comment]
你后台要设置一下微博的账号密码，就可以了，这里面要用微博的cookie
